openapi: 3.0.0
info:
  title: CCS eSourcing Jaggaer Client API
  version: 0.0.1-SNAPSHOT
servers:
  # Added by API Auto Mocking Plugin
  - description: SwaggerHub API Auto Mocking
    url: https://virtserver.swaggerhub.com/joeraymond-roweit/Jaggaer_Client_API/0.0.1-SNAPSHOT
  - description: Jaaager Pre-Prod Environment
    url: >-
      https://crowncommercialservice-ws02-prep.bravosolution.co.uk/esop/jint/api/public/ja/v1/
tags:
  - name: Projects
    description: Jaggaer Projects API
  - name: Rfx
    description: Jaggaer RFX API
  - name: RfxWorkflows
    description: Jaggaer RFXWORKFLOW API
paths:
  /projects:
    post:
      tags:
        - Projects
      summary: Create Jaggaer Project
      description: Creates a Project in Jaggaer.
      operationId: createProject
      responses:
        '201':
          description: project created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProjectResponse'
        '403':
          description: >-
            The API key and request syntax was valid but the server is refusing
            to complete the request. This can happen if you are trying to read
            or write to objects or properties that you do not have access to.
          content:
            application/vnd.api+json:
              schema:
                properties:
                  error:
                    type: string
                    example: You are not authorized to access this page.
                    default: You are not authorized to access this page.
        '404':
          description: >-
            Not found. Either the request method and path supplied do not
            specify a known action in the API, or the object specified by the
            request does not exist.
          content:
            application/vnd.api+json:
              schema:
                properties:
                  error:
                    type: string
                    example: The resource you were looking for could not be found.
                    default: The resource you were looking for could not be found.
        default:
          description: successful operation
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Projects'
        description: Created sourcing object
        required: true
  /rfxs:
    post:
      tags:
        - Rfx
      summary: Create an RFX for invitiation linked to a project
      description: Creates a CCS RFX for invitiation linked to a project.
      operationId: createRFX
      responses:
        '201':
          description: rfx created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RfxResponse'
        '403':
          description: >-
            The API key and request syntax was valid but the server is refusing
            to complete the request. This can happen if you are trying to read
            or write to objects or properties that you do not have access to.
          content:
            application/vnd.api+json:
              schema:
                properties:
                  error:
                    type: string
                    example: You are not authorized to access this page.
                    default: You are not authorized to access this page.
        '404':
          description: >-
            Not found. Either the request method and path supplied do not
            specify a known action in the API, or the object specified by the
            request does not exist.
          content:
            application/vnd.api+json:
              schema:
                properties:
                  error:
                    type: string
                    example: The resource you were looking for could not be found.
                    default: The resource you were looking for could not be found.
        default:
          description: successful operation
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Rfxs'
        description: Created rfx object
        required: true
  /rfxworkflows/invalidate:
    post:
      tags:
        - RfxWorkflows
      summary: Invalidate an RFX
      description: Invalidates a CCS RFX.
      operationId: invalidateRFX
      responses:
        '201':
          description: rfx invalidated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RfxInvalidationResponse'
        '403':
          description: >-
            The API key and request syntax was valid but the server is refusing
            to complete the request. This can happen if you are trying to read
            or write to objects or properties that you do not have access to.
          content:
            application/vnd.api+json:
              schema:
                properties:
                  error:
                    type: string
                    example: You are not authorized to access this page.
                    default: You are not authorized to access this page.
        '404':
          description: >-
            Not found. Either the request method and path supplied do not
            specify a known action in the API, or the object specified by the
            request does not exist.
          content:
            application/vnd.api+json:
              schema:
                properties:
                  error:
                    type: string
                    example: The resource you were looking for could not be found.
                    default: The resource you were looking for could not be found.
        default:
          description: successful operation
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RfxInvalidate'
        description: Invalidate rfx object
        required: true
components:
  schemas:
    Projects:
      type: object
      required:
        - operationCode
        - project
      properties:
        operationCode:
          type: string
          example: CREATEUPDATE
        project:
          $ref: '#/components/schemas/Project'
    Project:
      type: object
      required:
        - tender
      properties:
        tender:
          $ref: '#/components/schemas/Tender'
    Tender:
      type: object
      required:
        - title
        - buyerCompany
        - projectOwner
        - additionalInfoList
      properties:
        tenderReferenceCode:
          type: string
          example: project_1078
        title:
          type: string
          example: Test Project 123
        buyerCompany:
          $ref: '#/components/schemas/BuyerCompany'
        projectOwner:
          $ref: '#/components/schemas/ProjectOwner'
        sourceTemplateReferenceCode:
          type: string
          example: project_609
        projectType:
          type: string
          example: CCS_PROJ
        additionalInfoList:
          $ref: '#/components/schemas/AdditionalInfoList'
    BuyerCompany:
      type: object
      required:
        - id
      properties:
        id:
          type: string
          example: '51435'
    ProjectOwner:
      type: object
      required:
        - login
      properties:
        login:
          type: string
          example: user@crowncommercial.gov.uk
    OwnerUser:
      type: object
      required:
        - login
      properties:
        login:
          type: string
          example: sro-ccs
    AdditionalInfoList:
      type: object
      properties:
        additionalInfo:
          type: array
          items:
            $ref: '#/components/schemas/AdditionalInfoItem'
    AdditionalInfoItem:
      type: object
      properties:
        name:
          type: string
          example: Procurement Reference
        values:
          $ref: '#/components/schemas/Values'
    Values:
      type: object
      properties:
        value:
          type: array
          items:
            $ref: '#/components/schemas/ValueItem'
    ValueItem:
      type: object
      properties:
        value:
          type: object
          example: '324233324'
    Rfxs:
      type: object
      required:
        - operationCode
        - rfx
      properties:
        operationCode:
          type: string
          example: CREATEUPDATE
        rfx:
          $ref: '#/components/schemas/Rfx'
    Rfx:
      type: object
      required:
        - rfxSetting
        - rfxAdditionalInfoList
      properties:
        rfxSetting:
          $ref: '#/components/schemas/RfxSetting'
        rfxAdditionalInfoList:
          $ref: '#/components/schemas/RfxAdditionalInfoList'
    RfxSetting:
      type: object
      required:
        - tenderReferenceCode
        - shortDescription
        - buyerCompany
        - ownerUser
        - value
        - publishDate
        - closeDate
      properties:
        rfiFlag:
          type: string
          example: "1"
        rfxReferenceCode:
          type: string
          example: itt_597
        tenderReferenceCode:
          type: string
          example: projetct_1002
        shortDescription:
          type: string
          example: ITT Test 03122019 Attempt 3
        buyerCompany:
          $ref: '#/components/schemas/BuyerCompany'
        ownerUser:
          $ref: '#/components/schemas/OwnerUser'
        templateReferenceCode:
          type: string
          example: itt_543
        value:
          type: string
          example: '9000'
        valueCurrency:
          type: string
          example: GBP
        bidsCurrency:
          type: string
          example: GBP
        qualEnvStatus:
          type: string
          example: '0'
        techEnvStatus:
          type: string
          example: '1'
        commEnvStatus:
          type: string
          example: '0'
        publishDate:
          type: string
          example: '2019-08-20T13:54:32.000+00:00'
        closeDate:
          type: string
          example: '2019-08-30T13:54:32.000+00:00'
        rfxType:
          type: string
          example: STANDARD_PQQ
        visibilityEGComments:
          type: string
          example: '1'
        rankingStrategy:
          type: string
          example: BEST_TECHNICAL_SCORE
    RfxAdditionalInfoList:
      type: object
      properties:
        additionalInfo:
          type: array
          items:
            $ref: '#/components/schemas/RfxAdditionalInfoItem'
    RfxAdditionalInfoItem:
      type: object
      properties:
        name:
          type: string
          example: Procurement Route
        values:
          $ref: '#/components/schemas/RfxValues'
    RfxValues:
      type: object
      properties:
        value:
          type: array
          items:
            $ref: '#/components/schemas/RfxValueItem'
    RfxValueItem:
      type: object
      properties:
        value:
          type: object
          example: Open Market
    RfxResponse:
      type: object
      properties:
        returnCode:
          type: integer
          example: 0
        returnMessage:
          type: string
          example: OK
        rfxId:
          type: string
          example: rfq_47310
        rfxReferenceCode:
          type: string
          example: itt_534
    ProjectResponse:
      type: object
      properties:
        returnCode:
          type: integer
          example: 0
        returnMessage:
          type: string
          example: OK
        tenderCode:
          type: string
          example: tender_39483
        tenderReferenceCode:
          type: string
          example: project_1002
    RfxInvalidate:
      type: object
      required:
        - rfxReferenceCode
        - operatorUser
      properties:
        rfxReferenceCode:
          type: string
          example: itt_725
        operatorUser:
          $ref: '#/components/schemas/OperatorUser'
    OperatorUser:
      type: object
      required:
        - id
      properties:
        id:
          type: string
          example: '89512'
    RfxInvalidationResponse:
      type: object
      properties:
        returnCode:
          type: integer
          example: 0
        returnMessage:
          type: string
          example: OK
        rfxId:
          type: string
          example: rfq_50487
        rfxReferenceCode:
          type: string
          example: itt_725
        initialStatusCode:
          type: integer
          example: 300
        initialStatus:
          type: string
          example: Running
        finalStatusCode:
          type: integer
          example: 1000
        finalStatus:
          type: string
          example: Invalidated
        reopenRound:
          type: integer
          example: 0
        numInvolvedSuppliers:
          type: integer
          example: 0
        numRespondedSuppliers:
          type: integer
          example: 0
        numExcludedSuppliers:
          type: integer
          example: 0
        qualEnvStatus:
          type: integer
          example: 0
        techEnvStatus:
          type: integer
          example: 1
        commEnvStatus:
          type: integer
          example: 0
        publishDate:
          type: string
          example: "2021-03-12T09:01:40.000Z"
        closeDate:
          type: string
          example: "2021-05-28T11:00:00.000Z"
  securitySchemes:
    oAuthClientCredentials:
      type: oauth2
      flows:
        clientCredentials:
          tokenUrl: >-
            https://crowncommercialservice-ws02-prep.bravosolution.co.uk/esop/jint/api/public/v1/tokens/
          scopes: {}
security:
  - oAuthClientCredentials: []