language: java
jdk:
  - openjdk11
cache:
  - $HOME/.m2
script:
  - mvn verify
deploy:
    #
    # dev - we don't auto deploy into dev, it is used for manual pushes only
    #
      
    #
    # sandbox
    #
  - provider: cloudfoundry
    api: https://api.london.cloud.service.gov.uk
    username: paul.illingworth+ccs-esourcing-sandbox@roweit.co.uk
    password:
      secure: bVK3pAaQtX2tiDkrSUUNYitbETGBbMRk7NcbXFnRqwnGf+HAU0+8c8YfQkqUkD0s9ivrqPHNufVFKRuLl91vYaJOUBYQC3kSdeHVbbSRVf4x/mlvO6VIVqz1SsbEXsccCi9v8YLp7Zp/ljZZvdgKW6N1mW3QkSyLusmL5QBV9JM+9JnNpJ4UCnFMuCCb+1r7FKSSpsGOS8UOgB0MCdHAg5yddiYc5cEkPIz9WQAwVq0dhmOKjzShXrEnBTs7gBCsCEB4A64l5tYIxu5yuWh81STpwhd91zKvcZtbKH5eSZNVn4Pj3b4PfyV9/DGnL0+U/fHV/B1PZ2cqwy95Ihru6B7fUW31eTH+yWjIG//na4VOfTD/THuxcznoZPnMhSmZLXtIvDF4GSY2bQoVBQrssO0Yrv5xWJDMFX7BCeZpxADIX75LXSE+asGCZC0riPP+wsq2ncGMqy0VnjXoPPcktAvpLIu15SoYJC/afIie34Shp5uAyzizXNfrlZdkQdAIiGmkN417xuEUjD1tYvJEl19+1EUhaxMvpelTucLkAv9/ywMz+DzEuDwrx1qaPWxzE6DWmCVZZBh9yG6QbPdrno+vPfcB6N7rp3WbGHcB+ZQnLrwxCmzPDK5wsTXo6Z442P7TfcDXokpO+M5zFPNQVlQ7f4ncZS7JoOrKQxU0w0g=
    organization: ccs-esourcing-tenders-api
    space: sandbox
    manifest: manifest-staging.yml
    on:
      repo: Crown-Commercial-Service/ccs-esourcing-tenders-api
      branch: deploy/sandbox
    skip_cleanup: 'true'
    
    #
    # test
    #
  - provider: cloudfoundry
    api: https://api.london.cloud.service.gov.uk
    username: paul.illingworth+ccs-esourcing-test@roweit.co.uk
    password:
      secure: bVK3pAaQtX2tiDkrSUUNYitbETGBbMRk7NcbXFnRqwnGf+HAU0+8c8YfQkqUkD0s9ivrqPHNufVFKRuLl91vYaJOUBYQC3kSdeHVbbSRVf4x/mlvO6VIVqz1SsbEXsccCi9v8YLp7Zp/ljZZvdgKW6N1mW3QkSyLusmL5QBV9JM+9JnNpJ4UCnFMuCCb+1r7FKSSpsGOS8UOgB0MCdHAg5yddiYc5cEkPIz9WQAwVq0dhmOKjzShXrEnBTs7gBCsCEB4A64l5tYIxu5yuWh81STpwhd91zKvcZtbKH5eSZNVn4Pj3b4PfyV9/DGnL0+U/fHV/B1PZ2cqwy95Ihru6B7fUW31eTH+yWjIG//na4VOfTD/THuxcznoZPnMhSmZLXtIvDF4GSY2bQoVBQrssO0Yrv5xWJDMFX7BCeZpxADIX75LXSE+asGCZC0riPP+wsq2ncGMqy0VnjXoPPcktAvpLIu15SoYJC/afIie34Shp5uAyzizXNfrlZdkQdAIiGmkN417xuEUjD1tYvJEl19+1EUhaxMvpelTucLkAv9/ywMz+DzEuDwrx1qaPWxzE6DWmCVZZBh9yG6QbPdrno+vPfcB6N7rp3WbGHcB+ZQnLrwxCmzPDK5wsTXo6Z442P7TfcDXokpO+M5zFPNQVlQ7f4ncZS7JoOrKQxU0w0g=
    organization: ccs-esourcing-tenders-api
    space: dev
    manifest: manifest-test.yml
    on:
      repo: Crown-Commercial-Service/ccs-esourcing-tenders-api
      branch: deploy/test
    skip_cleanup: 'true'
  
    #
    # uat, pre-prod, prod etc - not yet defined
    #
