language: java
jdk:
  - openjdk11
cache:
  - $HOME/.m2
script:
  - mvn verify
deploy:
  - provider: cloudfoundry
    api: https://api.london.cloud.service.gov.uk
    username: paul.illingworth+ccs-esourcing-sandbox@roweit.co.uk
    password:
      secure: bVK3pAaQtX2tiDkrSUUNYitbETGBbMRk7NcbXFnRqwnGf+HAU0+8c8YfQkqUkD0s9ivrqPHNufVFKRuLl91vYaJOUBYQC3kSdeHVbbSRVf4x/mlvO6VIVqz1SsbEXsccCi9v8YLp7Zp/ljZZvdgKW6N1mW3QkSyLusmL5QBV9JM+9JnNpJ4UCnFMuCCb+1r7FKSSpsGOS8UOgB0MCdHAg5yddiYc5cEkPIz9WQAwVq0dhmOKjzShXrEnBTs7gBCsCEB4A64l5tYIxu5yuWh81STpwhd91zKvcZtbKH5eSZNVn4Pj3b4PfyV9/DGnL0+U/fHV/B1PZ2cqwy95Ihru6B7fUW31eTH+yWjIG//na4VOfTD/THuxcznoZPnMhSmZLXtIvDF4GSY2bQoVBQrssO0Yrv5xWJDMFX7BCeZpxADIX75LXSE+asGCZC0riPP+wsq2ncGMqy0VnjXoPPcktAvpLIu15SoYJC/afIie34Shp5uAyzizXNfrlZdkQdAIiGmkN417xuEUjD1tYvJEl19+1EUhaxMvpelTucLkAv9/ywMz+DzEuDwrx1qaPWxzE6DWmCVZZBh9yG6QbPdrno+vPfcB6N7rp3WbGHcB+ZQnLrwxCmzPDK5wsTXo6Z442P7TfcDXokpO+M5zFPNQVlQ7f4ncZS7JoOrKQxU0w0g=
    organization: ccs-esourcing-tenders-api
    space: sandbox
    manifest: manifest-sandbox.yml
    on:
      repo: Crown-Commercial-Service/ccs-esourcing-tenders-api
      branch: deploy/sandbox
    skip_cleanup: true
  - provider: cloudfoundry
    api: https://api.london.cloud.service.gov.uk
    username: paul.illingworth+ccs-esourcing-test@roweit.co.uk
    password:
      secure: ocPOF8QusanbCRGZEUid62q8kljfm0JVmnsr1bRAOzwYbemBOeBmmseDby/juGSMw+ZC0SQ+soQR79PeGtisPmxKBbB2i2IeAp7QGZQgJ2bD84sosdwTqPaQ/OCjjh6C8XqzvHOc4E4SnLgVQOR6ZS3GsqyqJ4ACtYi4DHaNCE6UdsnuEBmBIK6LbWRgYFk1srhkusBwzW80Zo1NAIFSVpODcdstdKW+inZaKkaq5K2wPP7bUEvQW2YMvuTAaJttBnDscGLf6YD2zb9jf47fEqlHA9ZHjhwUc++l3JAPMqc6KuxDE4J9NR+M8Xl+CxplKSr76xrs7khhGHAkG21ASqVfGoU1zQHZ+BMV1dTRBXE9CJLpotdnsKfQp/cB3JGarpydd7FuieT8h7dosGYMQ8vKpoC5bx+qOeDjS7Y1kIX1PZhz5zpLrALjCpJUpLI2hv6NLTurecFec2ibZSTXmQ1G69xTDd8b4v/CSkD4IqutNoAVkqvT68o9NNnqoxWQzxgOkQPFn1AiYYaK9MYUCTgNPYvcI46jx6ghOGtVhnhIEPZNcUzpmHEmUBVmcTzEnUFLNM1gLAl/tiVNZohOycu8zCunJ+MBYnL4ZSFOjdxU4bSkIJ7k+exhNXNmdhS2SdEcRzwuuXWujLXPfx754p1aCdpOiPZ1Wz/a3Fq8KKc=
    organization: ccs-esourcing-tenders-api
    space: Test
    manifest: manifest-test.yml
    on:
      repo: Crown-Commercial-Service/ccs-esourcing-tenders-api
      branch: deploy/test
    skip_cleanup: 'true'      
