language: java
jdk:
  - openjdk11
deploy:
  provider: cloudfoundry
  api: https://api.london.cloud.service.gov.uk
  username: joe.raymond@roweit.co.uk
  password:
    secure: HQ+t6bI7H8jkPfTLE1lneX4CUd+Cr2GsWkeQXjYrXvEpECz+7ABLVFEagLfAUaQ4WrgVh7SIVFwzVEIn7dhBX+0df7QUop5tF1cY/p0R10O3pRLAf2Ah5gU7KGZ6CwCMP3Bth0oZX0uuxxeroxEduxEzYu6aOS44B5HJoTHAl7ysgqOEHFpY3Yol8yQEil6wyIdl6bsfZ65jRrjREsSRk6Av7M1PF83/nHKNTRJnGsIa/U/tvNxsUlvidkMyQNy19vdJoB8fX/ynftTMv2kMseZyjeXugGhIe4iGmJdllWigXK3t2fYWq2yDLecQqj01l58isBl4s70G78DcGIvx4zriWnwT5L+u2v/XydTaw6jy8QNQQkh+riRQPCDTXNUDRVZWuVbqWngoF+OxTczh7fGZGwNuuQhWwSSfPZdNiRffJGaRgbkVxFjJFKkisPlX0D3BbgjUZeJ4SE0De/5UyWogcFJkFOrIChGqd/Fz8uV4ozo8QleGkfkK/06KsoRtb5mJ2naOfweVDY1MskyIXBsAEc+YYMTG6RTlhVb/kzgaSDnh09bcSf4rRcfjlXJzs0yfexjI7H/RMhAoGlkdMSveh+LkLaXQ2Yd1t9EPN2KfT/8QnMVvq2Zc7b1XQSvaNm79YfxBp1cBniqC4dpoxFL6MDXA+1EnmFtwAit5t4Y=
  organization: ccs-esourcing-tenders-api
  space: sandbox
  on:
    repo: RoweIT/ccs-esourcing-tenders-api
    branch: main
  skip_cleanup: 'true'
