openapi: 3.0.0
info:
  title: CCS eSourcing Client
  version: 0.0.1-SNAPSHOT

servers:
  # Added by API Auto Mocking Plugin
  - description: SwaggerHub API Auto Mocking
    url: https://virtserver.swaggerhub.com/crown-commercial-service/ccs-esourcing-client/0.0.1-SNAPSHOT

tags:
  - name: ProjectITT
  - name: ITT Status

paths:

  /tenders/ProcurementProjects/salesforce:
    post:
      tags:
        - Salesforce
      summary: Create a new case in Jaggaer - Salesforce will call Jaggaer
      description: >-
        Creates a new CCS procurement case in the Jaggaer eSourcing platform.
      operationId: createProcurementCase
      responses:
        201:
          description: Success (for object creation). Its information is available in the data field at the top level of the response body. The API URL where the object can be retrieved is also returned in the Location header of the response.
          content:
            application/json:
              schema:
                type: object
                properties:
                  tenderReferenceCode:
                    type: string
                    description: project code (project id)
                    example: "project_1063"
                  rfxReferenceCode:
                    type: string
                    description: the itt code (tender id)
                    example: "itt_586"
        403:
          description: The API key and request syntax was valid but the server is refusing to complete the request. This can happen if you are trying to read or write to objects or properties that you do not have access to.
          content:
            application/vnd.api+json:
              schema:
                $ref: '#/components/schemas/inline_response_403'
        404:
          description: Not found. Either the request method and path supplied do not specify a known action in the API, or the object specified by the request does not exist.
          content:
            application/vnd.api+json:
              schema:
                $ref: '#/components/schemas/inline_response_404'
        500:
          description: An unknown server error has occurred.
          content:
            application/vnd.api+json:
              schema:
                $ref: '#/components/schemas/inline_response_500'
        default:
          description: successful operation
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ProjectTender'
        description: Created sourcing object
        required: true

  /tenders/ProcurementProjects/updateProcurementStage:
    post:
      tags:
        - ITT Status
      description: Update Procurement Project stage
      operationId: updateCaseRFxStatus
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RfxStatusList'
      responses:
        200:
          description: ok
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RfxStatus200ResponseList'
        401:
          description: No authorization. A valid API key was not provided with the request, so the API could not associate a user with the request.
          content:
            application/vnd.api+json:
              schema:
                $ref: '#/components/schemas/inline_response_401'
        403:
          description: The API key and request syntax was valid but the server is refusing to complete the request. This can happen if you are trying to read or write to objects or properties that you do not have access to.
          content:
            application/vnd.api+json:
              schema:
                $ref: '#/components/schemas/inline_response_403'

components:
  schemas:

    ProjectTender:
      type: object
      required:
        - subject
        - procurementReference
        - rfx
      properties:
        tenderReferenceCode:
          type: string
          nullable: false
          example: project_1078
        subject:
          type: string
          example: Project for Provision of Face Masks
        procurementReference:
          type: string
          example: "324233324"
        rfx:
          $ref: '#/components/schemas/Rfx'

    Rfx:
      title: Rfx
      type: object
      required:
        - rfxSetting
        - rfxAdditionalInfo
      properties:
        rfxSetting:
          $ref: '#/components/schemas/RfxSetting'
        rfxAdditionalInfo:
          $ref: '#/components/schemas/RfxAdditionalInfo'

    RfxSetting:
      title: RfxSetting
      type: object
      required:
        - shortDescription
        - value
        - publishDate
        - closeDate
      properties:
        shortDescription:
          type: string
          example: RFQ for Provision of PPE
        value:
          type: string
          example: "9000"
        valueCurrency:
          type: string
          example: GBP
        bidsCurrency:
          type: string
          example: GBP
        qualEnvStatus:
          type: string
          example: 0
        techEnvStatus:
          type: string
          example: 1
        commEnvStatus:
          type: string
          example: 0
        publishDate:
          type: string
          example: "2021-01-28T12:00:00.000+00:00"
        closeDate:
          type: string
          example: "2021-02-27T12:00:00.000+00:00"
        visibilityEGComments:
          type: string
          example: 1
        rankingStrategy:
          type: string
          example: BEST_TECHNICAL_SCORE

    RfxAdditionalInfo:
      title: RfxAdditionalInfo
      type: object
      required:
        - name
        - value
      properties:
        name:
          type: string
          example: Procurement Route
        value:
          type: string
          example: Call Off (Competition)

    RfxStatusList:
      type: array
      items:
        $ref: '#/components/schemas/RfxStatusItem'

    RfxStatusItem:
      title: RfxStatus
      required:
        - actualStartDate
        - closingTime
        - procurementReference
        - stage
        - tenderEndDate
      type: object
      properties:
        procurementReference:
          type: string
          example: CO0001
        stage:
          type: string
          example: ITT Live
        actualStartDate:
          type: string
          example: "2020-03-27T15:38:53.000+0000"
        tenderEndDate:
          type: string
          example: "2020-03-27T15:38:53.000+0000"
        closingTime:
          type: string
          example: "14:38:53.000Z"

    RfxStatus200ResponseList:
      type: array
      items:
        $ref: '#/components/schemas/RfxStatus200Response'

    RfxStatus200Response:
      type: object
      properties:
        procurement_reference:
          type: string
          example: CO0001
        isSuccess:
          type: string
          example: "true"
        errorMessage:
          type: string
          example: ""

    inline_response_403:
      type: object
      properties:
        error:
          type: string
          example: You are not authorized to access this page.
          default: You are not authorized to access this page.

    inline_response_404:
      type: object
      properties:
        error:
          type: string
          example: The resource you were looking for could not be found.
          default: The resource you were looking for could not be found.

    inline_response_500:
      type: object
      properties:
        error:
          type: string
          example: An unknown error has occurred.
          default: An unknown error has occurred.

    inline_response_401:
      type: object
      properties:
        error:
          type: string
          example: The resource you were looking for requires L2 authentication.
          default: No authorization. A valid API key was not provided with the request, so the API could not associate a user with the request.

  securitySchemes:
    ApiKeyAuth:        # arbitrary name for the security scheme
      type: apiKey
      in: header       # can be "header", "query" or "cookie"
      name: x-api-key

security:
  - ApiKeyAuth: []