openapi: 3.0.0

info:
  description: This is a simple API
  version: "1.0.0"
  title: Crown Commercial Service
servers:
  # Added by API Auto Mocking Plugin
  - description: SwaggerHub API Auto Mocking
    url: https://virtserver.swaggerhub.com/joeraymond-roweit/Tenders/1.0.0

paths:
  /projects:
    post:
      tags:
        - PROJECTS
      summary: Create Jaggaer Project
      description: >-
        Creates a Project in Jaggaer.
      operationId: createProject
      responses:
        '201':
          description: project created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProjectResponse'
        '403':
          description: The API key and request syntax was valid but the server is refusing to complete the request. This can happen if you are trying to read or write to objects or properties that you do not have access to.
          content:
            application/vnd.api+json:
              schema:
                properties:
                  error:
                    type: string
                    example: You are not authorized to access this page.
                    default: You are not authorized to access this page.
        '404':
          description: Not found. Either the request method and path supplied do not specify a known action in the API, or the object specified by the request does not exist.
          content:
            application/vnd.api+json:
              schema:
                properties:
                  error:
                    type: string
                    example: The resource you were looking for could not be found.
                    default: The resource you were looking for could not be found.
        default:
          description: successful operation
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Projects'
        description: Created sourcing object
        required: true
  /rfxs:
    post:
      tags:
        - RFX
      summary: Create an RFX for invitiation linked to a project
      description: >-
        Creates a CCS RFX for invitiation linked to a project.
      operationId: createRFX
      responses:
        '201':
          description: project created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RfxResponse'
        '403':
          description: The API key and request syntax was valid but the server is refusing to complete the request. This can happen if you are trying to read or write to objects or properties that you do not have access to.
          content:
            application/vnd.api+json:
              schema:
                properties:
                  error:
                    type: string
                    example: You are not authorized to access this page.
                    default: You are not authorized to access this page.
        '404':
          description: Not found. Either the request method and path supplied do not specify a known action in the API, or the object specified by the request does not exist.
          content:
            application/vnd.api+json:
              schema:
                properties:
                  error:
                    type: string
                    example: The resource you were looking for could not be found.
                    default: The resource you were looking for could not be found.
        default:
          description: successful operation
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Rfxs'
        description: Created rfx object
        required: true
components:
  schemas:
    Projects:
      type: object
      required:
        - operationCode
        - project
      properties:
        operationCode:
          type: string
          example: Create
        project:
          $ref: '#/components/schemas/Project'
    Rfxs:
      type: object
      required:
        - operationCode
        - rfx
      properties:
        operationCode:
          type: string
          example: Create
        rfx:
          $ref: '#/components/schemas/Rfx'
    Project:
      type: object
      required:
        - tender
      properties:
        tender:
          $ref: '#/components/schemas/Tender'
    Tender:
      type: object
      properties:
        title:
          type: string
          example: Test Project 123
        buyerCompany:
          $ref: '#/components/schemas/BuyerCompany'
        projectType:
          type: string
          example: CCS_PROJ
        additionalInfoList:
          $ref: '#/components/schemas/AdditionalInfoList'
    BuyerCompany:
      type: object
      required:
        - id
      properties:
        id:
          type: string
          example: "51435"
    OwnerUser:
      type: object
      required:
        - login
      properties:
        login:
          type: string
          example: sro-ccs
    AdditionalInfoList:
      type: object
      properties:
        additionalInfo:
          type: array
          items:
            $ref: '#/components/schemas/AdditionalInfo'
    AdditionalInfo:
      type: object
      properties:
        name:
          type: string
          example: Procurement Reference
        type:
          type: string
          example: Text
        visibleToSupplier:
          type: integer
          example: 1
        values:
          $ref: '#/components/schemas/Value'
    Value:
      type: object
      properties:
        value:
          type: array
          items:
            $ref: '#/components/schemas/Valuelist'
    Valuelist:
      type: object
      properties:
        value:
          type: object
          example: "324233324"
    Rfx:
      type: object
      required:
        - rfxSetting
        - rfxAdditionalInfoList
      properties:
        rfxSetting:
          $ref: '#/components/schemas/RfxSetting'
        rfxAdditionalInfoList:
          $ref: '#/components/schemas/RfxAdditionalInfoList'
    RfxSetting:
      type: object
      required:
        - rfiFlag
        - tenderReferenceCode
        - shortDescription
        - longDescription
        - buyerCompany
        - ownerUser
        - value
        - valueCurrency
        - bidsCurrency
        - qualEnvStatus
        - techEnvStatus
        - commEnvStatus
        - publishDate
        - closeDate
        - rfxType
        - autoCreateTender
      properties:
        rfiFlag:
          type: string
          example: "0"
        tenderReferenceCode:
          type: string
          example: projetct_1002
        shortDescription:
          type: string
          example: ITT Test 03122019 Attempt 3
        longDescription:
          type: string
          example: ITT Test 03122019 Long Description
        buyerCompany:
          $ref: '#/components/schemas/BuyerCompany'
        ownerUser:
          $ref: '#/components/schemas/OwnerUser'
        value:
          type: string
          example: "9000"
        valueCurrency:
          type: string
          example: GBP
        bidsCurrency:
          type: string
          example: GBP
        qualEnvStatus:
          type: string
          example: "0"
        techEnvStatus:
          type: string
          example: "0"
        commEnvStatus:
          type: string
          example: "1"
        publishDate:
          type: string
          example: "2019-08-20T13:54:32.000+00:00"
        closeDate:
          type: string
          example: "2019-08-30T13:54:32.000+00:00"
        rfxType:
          type: string
          example: STANDARD_ITT
        autoCreateTender:
          type: string
          example: "0"
    RfxAdditionalInfoList:
      type: object
      properties:
        additionalInfo:
          type: array
          items:
            $ref: '#/components/schemas/RfxAdditionalInfo'
    RfxAdditionalInfo:
      type: object
      properties:
        name:
          type: string
          example: Procurement Route
        type:
          type: string
          example: "5"
        visibleToSupplier:
          type: integer
          example: 0
        label:
          type: string
          example: Procurement Route
        labelLocale:
          type: string
          example: en_GB
        values:
          $ref: '#/components/schemas/RfxValue'
    RfxValue:
      type: object
      properties:
        value:
          type: array
          items:
            $ref: '#/components/schemas/RfxValuelist'
    RfxValuelist:
      type: object
      properties:
        value:
          type: object
          example: Open Market
    RfxResponse:
      type: object
      properties:
        returnCode:
          type: integer
          example: 0
        returnMessage:
          type: string
          example: OK
        rfxId:
          type: string
          example: rfq_47310
        rfxReferenceCode:
          type: string
          example: itt_534
    ProjectResponse:
      type: object
      properties:
        returnCode:
          type: integer
          example: 0
        returnMessage:
          type: string
          example: OK
        tenderCode:
          type: string
          example: tender_39483
        tenderReferenceCode:
          type: string
          example: project_1002